# Generated by Django 4.0.4 on 2022-04-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='candidatos',
            field=models.IntegerField(default=0, verbose_name='Candidatos'),
        ),
    ]
