# Generated by Django 4.0.4 on 2022-05-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_vaga_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='cidade',
            field=models.CharField(default='Jataí', max_length=1024, verbose_name='Cidade'),
            preserve_default=False,
        ),
    ]
