# Generated by Django 4.0.4 on 2022-05-04 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
        ('empresa', '0006_empresa_logo_vaga_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatosVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data Cadatro')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.vaga')),
            ],
        ),
    ]
